pub mod test_longest_continuous_substring;
pub mod test_min_end;
pub mod test_majority_element;
mod test_is_valid;
mod test_satisfies_conditions;
mod test_min_substring_in_partition;
mod test_latest_time_catch_the_bus;
mod test_remove_stars;
mod test_check_digital;
mod test_dyn_error;
mod test_sum_digit_differences;
mod test_max_strength;
mod test_count_ways;
mod test_check_two_chess_board;
mod test_max_consecutive_answers;
mod test_count_special_numbers;
mod test_score_of_string;
mod test_difference_of_sum;
mod test_dest_city;
mod test_time_required_to_buy;
mod test_seat_manager;
mod test_stable_mountains;
mod test_number_of_pairs;
mod test_losing_player;